### PR TITLE
Fix always_populate_raw_post_data to be -1

### PR DESCRIPTION
**Pull request by RobLoach**
#12

via @andypost  ... Mind testing this out?

### CODE REVIEW

**Comment by andypost** [comment]
In progress of downloading ... building

PS: you'd better changed base container to alpine image to download less

**Comment by RobLoach** [comment]
@andypost There was some work to move towards that: https://github.com/RobLoach/docker-composer/pull/19 ... Would love your input there.

**Comment by andypost** [comment]
`
docker run --rm test /bin/sh
exec: "drush": executable file not found in $PATH
FATA[0000] Error response from daemon: Cannot start container b39ddf4280ddc65639d589021fd82afc59c5c9f6667916bd5d4149234224e516: [8] System error: exec: "drush": executable file not found in $PATH 
`

**Comment by andypost** [comment]
oh I missed to rebuild other ones

**Comment by andypost** [comment]
works!
and php images looks mostly ready for alpine)

**Comment by RobLoach** [comment]
Awesome! Thanks for testing it out :+1: . Come to think of this, I'll move this up to the composer container.

**Pull request closed without merging**
