### PR TITLE
Add Alpine variants for Drush.

### PR DESCRIPTION
**Pull request by sylus**
Build passes locally but will need the following P.R. which adds alpine support to composer to pass in travis:

https://github.com/RobLoach/docker-composer/pull/56

Edit: P.R. is merged just waiting for docker tags.

I added postgres support as well since is what I needed, let me know. ^_^

I didn't add 6,7 since it seems they will be dropped soon anyways.

### CODE REVIEW

**Comment by sylus** [comment]
I had to add `postgresql-dev` which is pretty heavy because of:

https://bugs.alpinelinux.org/issues/3642

If you want me to remove the postgresql add-ons I can just use them in my sub-container so let me know ^_^.

**Comment by RobLoach** [comment]
The base Composer images are still building in Docker Hub:
https://hub.docker.com/r/composer/composer/builds/

Once that's through, mind seeing if the Travis tests pass?

**Comment by sylus** [comment]
Re-triggered and tests look good! :)

**Comment by RobLoach** [comment]
Thanks! :+1:

**Pull request merged**
